FROM docker:18.06.1-ce

RUN apk add --no-cache gcc musl-dev openssl git go expect curl && \
    go install cmd/...

COPY . /src
WORKDIR /src
RUN chmod +x /src/run-tests.sh

CMD ["sh", "-c", "/src/run-tests.sh"]
