version: '3.2'


services:

  tests_local:
    image: thomasjpfan/docker-flow-swarm-listener-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/src
    networks:
      - dfsl_network

networks:
  dfsl_network: